# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
# Derived from scipy-notebook, with minor modification.  Original maintainer is
# the Jupyter Project.
FROM jupyter/minimal-notebook

# Minimal notebook for testing
MAINTAINER Kyle Shannon <kyle@pobox.com>

USER $NB_USER

WORKDIR $HOME

RUN echo "Hello, world!\n" > hello.txt
